map $http_user_agent $backend {
    default       "static";
    "~*curl"      "flask";
}

upstream flask {
    server api:8080;
}

upstream static {
    server static:80;
}

server {
    listen 80;
    server_name _;

    location / {
        proxy_pass http://$backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
